### ISSUE TITLE
C2QB using getAppNow scope

### ISSUE THREAD

**Issue by froztyco** [IntuitDeveloper/OAuth2-Go#1]
func ConnectToQuickbooks(w http.ResponseWriter, r *http.Request) {
	log.Println("inside connectToQuickbooks ")
	http.Redirect(w, r, PrepareUrl(config.OAuthConfig.GetAppNowScope, GenerateCSRF()), http.StatusSeeOther)
}

I believe this should be using the c2qb config setting.

**Comment by diana-derose** [comment]
Good catch, I have updated the scope.
